blank_issues_enabled: true
contact_links:
  - name: "ðŸ“– Documentation"
    url: https://github.com/luna-asksage/website-monitor/blob/main/README.md
    about: Read the documentation before creating an issue